---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: pacman-secret
  namespace: pacman
spec:
  encryptedData:
    pass: AgBaEGvX1B1ZmZjH4JJFyb4TtTQYRx1ED0vgho2NXJtkxitiZ4XhDOnlcoxRv/vAOU+kZ5ZqXTvELCfNrJCcD3+Wj4MX5uBLkYAOhLHcpmGmh98U/dlzKNEJJJryHJSqgttEYbp2o4XTl9x+AOFNaeJiooW21AIKe6YunzB8cTYO6VVnDmobwtg3ro8MSMevH5kzE2eEUPMhXju+lsa34ILfIoKHT6Wa2Qf13VtkbKdudWmUAKWE+TNIkEsyfv+0/8G5owW4z8QVSsAJKqke8ELAHIO06KOWg9Vbk3PJXfWScQsCXScI9O8HSDwP/NhAtUymx9N0kcPIJZW14dCSC+vjZrYDil6PZtw8MOYygJvrzTo2OnrEeqLlP4XK49lZtWY37exLCubCt5LkCBYLNvF9rbQSxTF6fHjUMj3YbISriA9tpizwCBuKmteD6w9JD9FvkQR1/o+n6msQ6JOY6L0EOpTMirMv8MRyHRvDn9jG4oxZqWrtGNfP0QN4W6myb1rd5eClewrfajoTjYQjXkJxExUMztLNHbM+AsjddG9EFHzaZBWT289MseyBrg44EqPbvAFJpFc0PRU0Wx4ZnHZRcHaNpI2PiLVctkgfxTNn/4q9CLZvyG+YDDdDi3bNwZLlE38ThF1fUWWJrr6vU7o38aVmxHqSs8chobLL/LAMayLI+1hngB0FIt4CAoIYu/hSlwFZ
    user: AgB80Z9xmXEKsjW7/CLREATxAUUJs9IpSLJEgvMmHh6vP7jMwf57Ir1UERMj7+6SLFxSa5mJpK/cumrMsNvPf89Nzbaz6Sq8vIWA+QFpppighEKmlPjsnkyvyuHe2mempuZA1hzF2TnpBJDoEVmjy7yWuB9APWcZtmVwzEla19u2LAd6feWZx5Qc8+M0dpZld8GNgsUaVWN6mgipaanqPhBXgQk6vnnwBqD/TVho7x1LPgy04+ghjrj8655xHhBKFZbiaRFdLUo5s0qvHoAEM4zixllHL3qLh0Q+NVv5sYIJDcMC/EUn810aXCIIdQ8pIPba95RHdzPf9bN+Ff/eMGZbRGyqIAH2mPFiBCrPZf2RCN2Xm2MkHMFb+m7e2wb9Bp/0D3w4n64XJSwXkvItIDZJiLUiKAyGWREnb7M8jQy/2O59/9BFfSSG/M458hr2tffM9KSrlB8S2yfTePrZpGtoYvPD1QufHRP4QjOSBu5aI+5MK6rN9zC7W2i7bTpSAncO+s8z5U344wa65dYdfJbrNh2vF15+MZm/XOrnEuTZAMcucYRlP0KdMD10JBUuquAKIS5nuRvZ6y3SosD/IWS4IVklDdjiTU6WNJm325SBRMOWePRf5lJT1gu2+318fg4u/NrhQZF6lEiWbnjgKLxL1g6G5raWA89Q9UFHv2poDvXEvaSCbsjnEu6t6PAucn6ewlKV0+U=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: pacman-secret
      namespace: pacman
    type: Opaque
